package model;
// Generated 01/07/2017 07:18:32 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * Pergunta generated by hbm2java
 */
@Entity
//@SecondaryTable(name = "usuario", pkJoinColumns = {@PrimaryKeyJoinColumn(name = "id")})
@Access(AccessType.FIELD)
public class Pergunta implements Serializable {

    @Id
    @SequenceGenerator(name = "seq_perg", allocationSize = 20, initialValue = 1)
    @GeneratedValue(generator = "seq_perg", strategy = GenerationType.AUTO)
    private Integer id;
    @Column(nullable = false)
    @Temporal(TemporalType.DATE)
    private Date dataPostagem;
    @Column(nullable = false)
    private String periodo;
    @Column(nullable = false)
    private String materia;
    @Column(nullable = false)
    private String textoPergunta;
    
    @OneToMany(mappedBy = "pergunta", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Resposta> respostas;
    
//    @Basic(fetch = FetchType.EAGER)
//    @Column(name = "nome", table = "usuario", nullable = false)
//    private String nomeUsuario;
    
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Usuario usuario;

    public Pergunta() {
    }

    public Pergunta(Date dataPostagem, String periodo, String materia, String textoPergunta) {
        this.dataPostagem = dataPostagem;
        this.periodo = periodo;
        this.materia = materia;
        this.textoPergunta = textoPergunta;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDataPostagem() {
        return dataPostagem;
    }

    public void setDataPostagem(Date dataPostagem) {
        this.dataPostagem = dataPostagem;
    }

    public String getPeriodo() {
        return periodo;
    }

    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    public String getMateria() {
        return materia;
    }

    public void setMateria(String materia) {
        this.materia = materia;
    }

    public String getTextoPergunta() {
        return textoPergunta;
    }

    public void setTextoPergunta(String textoPergunta) {
        this.textoPergunta = textoPergunta;
    }

    public List<Resposta> getRespostas() {
        return respostas;
    }

    public void setRespostas(List<Resposta> respostas) {
        this.respostas = respostas;
    }
//
//    public String getNomeUsuario() {
//        return nomeUsuario;
//    }
//
//    public void setNomeUsuario(String nomeUsuario) {
//        this.nomeUsuario = nomeUsuario;
//    }
//
    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
