package model;
// Generated 01/07/2017 07:18:32 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Resposta generated by hbm2java
 */
@Entity
//@SecondaryTable(name = "usuario", pkJoinColumns = {@PrimaryKeyJoinColumn(name = "id")})
@Access(AccessType.FIELD)
public class Resposta implements Serializable {

    @Id
    @SequenceGenerator(name = "seq_resp", allocationSize = 20, initialValue = 1)
    @GeneratedValue(generator = "seq_resp", strategy = GenerationType.AUTO)
    private Integer id;
    @Column(nullable = false)
    @Temporal(TemporalType.DATE)
    private Date dataPostagem;
    @Column(nullable = false)
    private String textoResposta;
    @Transient
    private String nomeUsuario;
    
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Pergunta pergunta;
    
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Usuario usuario;

    public Resposta() {
    }

    public Resposta(Date dataPostagem, String textoResposta) {
        this.dataPostagem = dataPostagem;
        this.textoResposta = textoResposta;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDataPostagem() {
        return dataPostagem;
    }

    public void setDataPostagem(Date dataPostagem) {
        this.dataPostagem = dataPostagem;
    }

    public String getTextoResposta() {
        return textoResposta;
    }

    public void setTextoResposta(String textoResposta) {
        this.textoResposta = textoResposta;
    }

    public String getNomeUsuario() {
        return usuario.getNome();
    }


    public Pergunta getPergunta() {
        return pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
