package model;
// Generated 01/07/2017 07:18:32 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Resposta generated by hbm2java
 */
@Entity
@Access(AccessType.FIELD)
public class Resposta implements Serializable {

    @Id
    @SequenceGenerator(name = "seq_usu", initialValue = 1, allocationSize = 20)
    @GeneratedValue(generator = "seq_usu", strategy = GenerationType.SEQUENCE)
    private Integer id;
    @Column(nullable = false)
    @Temporal(TemporalType.DATE)
    private Date dataPostagem;
    @Column(nullable = false)
    private String textoResposta;
    @Transient
    private String nomeUsuario;

    public Resposta() {
    }

    public Resposta(Date dataPostagem, String textoResposta) {
        this.dataPostagem = dataPostagem;
        this.textoResposta = textoResposta;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDataPostagem() {
        return dataPostagem;
    }

    public void setDataPostagem(Date dataPostagem) {
        this.dataPostagem = dataPostagem;
    }

    public String getTextoResposta() {
        return textoResposta;
    }

    public void setTextoResposta(String textoResposta) {
        this.textoResposta = textoResposta;
    }

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

}
