package model;
// Generated 01/07/2017 07:18:32 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Resposta generated by hbm2java
 */
@Entity
public class Resposta implements Serializable {

    @Id
    private Integer id;
    private Pergunta pergunta;
    private Usuario usuario;
    private Date datapostagem;
    private String textoresposta;

    public Resposta() {
    }

    public Resposta(Pergunta pergunta, Usuario usuario, Date datapostagem, String textoresposta) {
        this.pergunta = pergunta;
        this.usuario = usuario;
        this.datapostagem = datapostagem;
        this.textoresposta = textoresposta;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Pergunta getPergunta() {
        return this.pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Date getDatapostagem() {
        return this.datapostagem;
    }

    public void setDatapostagem(Date datapostagem) {
        this.datapostagem = datapostagem;
    }

    public String getTextoresposta() {
        return this.textoresposta;
    }

    public void setTextoresposta(String textoresposta) {
        this.textoresposta = textoresposta;
    }

}
