package model;
// Generated 01/07/2017 07:18:32 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Access(AccessType.FIELD)
public class Usuario implements Serializable {

    public Usuario(){}
    
    public Usuario(int id){
        this.id = id;
    }
    
    public Usuario(String nome, String email, String senha, String tipoUsuario) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.tipoUsuario = TipoUsuario.valueOf(tipoUsuario);
    }
    
    public Usuario(int id, String nome, String email, String senha, String tipoUsuario) {
        this.id = id;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.tipoUsuario = TipoUsuario.valueOf(tipoUsuario);
    }
    
    @Id
    @SequenceGenerator(name = "seq_usu", allocationSize = 20, initialValue = 1)
    @GeneratedValue(generator = "seq_usu", strategy = GenerationType.AUTO)
    private Integer id;
    @Column(nullable = false)
    private String nome;
    @Column(nullable = false)
    private String email;
    @Column(nullable = false)
    private String senha;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TipoUsuario tipoUsuario;
    
    @OneToMany(mappedBy = "usuario", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = false)
    private List<Pergunta> perguntas;
    
    @OneToMany(mappedBy = "usuario", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = false)
    private List<Resposta> respostas;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getTipoUsuario() {
        return this.tipoUsuario.toString();
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = TipoUsuario.valueOf(tipoUsuario);
    }

    public List<Pergunta> getPerguntas() {
        return perguntas;
    }

    public void setPerguntas(List<Pergunta> perguntas) {
        this.perguntas = perguntas;
    }
}
